#SCRIPT DO BANCO AQUI PARA USAR NO FLYWAY
#QUALQUER SCRIPT SEGUINDO A ORDEM V001 V002 RODARÁ NO BANCO EM SEQUENCIA CONTROLADO PELO FLYWAY

CREATE TABLE `usersystem`.`user`
(
    `id`       BIGINT       NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(45)  NOT NULL,
    `password` VARCHAR(20)  NOT NULL,
    `role`     VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8;